// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PigeonHostApi.
NSObject<FlutterMessageCodec> *PigeonHostApiGetCodec(void);

@protocol PigeonHostApi
- (nullable NSNumber *)deviceCheckIsSupportedWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)deviceCheckGenerateTokenWithCompletion:(void(^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
- (nullable NSNumber *)appAttestServiceIsSupportedWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)appAttestServiceGenerateKeyWithCompletion:(void(^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)appAttestServiceAttestKeyKeyId:(nullable NSString *)keyId clientDataHash:(nullable FlutterStandardTypedData *)clientDataHash completion:(void(^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
- (void)appAttestServiceGenerateAssertionKeyId:(nullable NSString *)keyId clientDataHash:(nullable FlutterStandardTypedData *)clientDataHash completion:(void(^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
@end

extern void PigeonHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PigeonHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
