name: ios_device_check
description: Flutter plugin for accessing the iOS DeviceCheck. Only supported on iOS 11.0 or newer.
version: 2.0.0+1
homepage: https://github.com/okadan/flutter-device-check/legacy

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosDeviceCheckPlugin
